name: oqba
description: 100% Offline PDF Scanner & Toolkit
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_mlkit_document_scanner: ^0.4.1
  syncfusion_flutter_pdf: ^28.1.33
  syncfusion_flutter_pdfviewer: ^28.1.33
  path_provider: ^2.1.4
  file_picker: ^8.0.0
  permission_handler: ^11.3.0
  share_plus: ^12.0.2
  pdfrx: ^1.0.0
  google_mlkit_text_recognition: ^0.13.0
  flutter_image_compress: ^2.1.0
  image_picker: ^1.1.0
  shared_preferences: ^2.2.2
  gal: ^2.3.0
  intl: ^0.20.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0F0F0F"
  adaptive_icon_foreground: "assets/icon.png"
